app/__init__.py
from flask import Flask
from flask.ext.flatpages import FlatPages
from flask.ext.frozen import Freezer
from flask.ext.bootstrap import Bootstrap
from config import config

pages = FlatPages()
freezer = Freezer()
bootstrap = Bootstrap()

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])

    freezer.init_app(app)
    pages.init_app(app)
    bootstrap.init_app(app)

    #register blueprints:
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    
    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
from flask import render_template
from . import main
from .. import pages, freezer


@main.route('/')
def home():
    posts = [page for page in pages]
    # Sort pages by date
    sorted_posts = sorted(posts, reverse=True,
        key=lambda page: page.meta['date'])
    return render_template('index.html', pages=sorted_posts)

@main.route('/<path:path>/')
def page(path):
    # 'path is the filename of a page, without the file extension'
    # e.g. "first-post"
    page = pages.get_or_404(path)
    return render_template('page.html', page=page)

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Data Weekly{% endblock %}

{% block head %}
{{ super() }}

{% endblock %}

{% block navbar %}
<div class="navbar" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.home') }}">
              Data Weekly
            </a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <!-- <li><a href="{{ url_for('main.home') }}">Home</a></li> -->
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
    <script type="text/javascript">
    $("#subscribe").click(function(e){
        e.preventDefault();
        var account = $("#account").val();
        console.log(account);
        $.post("http://106.14.25.2:5000/add?",{
            account:account
        },function(result){
            console.log(result);
            $("#result").text(result);
            $("#result").css("display","block");
        });
    })
    </script>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block page_content %}
<div class="jumbotron">
    <p>A weekly newsletter about Data Science.</p>
    <form class="form-inline" role="form">
        <div class="form-group">
            <label class="sr-only" for="exampleInputEmail2">Email address</label>
            <input type="email" class="form-control" id="account" placeholder="Enter email" name="account">
        </div>
        <button type="submit" class="btn btn-default" id="subscribe">Subscribe</button>
    </form>
    <div class="alert alert-info" role="alert" id="result" style="display: none;"></div>
</div>

<div class="page-header">
    <h3>Issues</h3>
</div>
<ul class="page-list">
  {% for page in pages %}
      <li><a href="{{ url_for('main.page', path=page.path) }}">
          {{ page.meta.title }}
      </a>- {{ page.meta.date }}</li>
  {% endfor %}
</ul>
{% endblock %}
<script type="text/javascript">
        $("#subscribe").click(function(e){
            e.preventDefault();
            var account = $("#account").val();
            console.log(account);
            $.post("http://106.14.25.2:5000/add?",{
                account:account
            },function(result){
                console.log(result);
                $("#result").text(result);
                $("#result").css("display","block");
            });
        })
</script>

app/templates/page.html
{% extends "base.html" %}

{% block page_content %}
<div class="page-header">
    <h1>{{ page.meta.title }} - <small>{{ page.meta.date }}</small></h1>

</div>
{{ page }}
{% endblock %}